version: '3.0'

services:
  mysql57:
    image: mysql:5.7 #https://hub.docker.com/r/library/mysql/tags/
    network_mode: "bridge"
    command: --sql_mode="NO_ENGINE_SUBSTITUTION" #https://github.com/docker-library/mysql/issues/149
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    container_name: gomato-mysql
  elasticsearch:
    image: elasticsearch:latest
    container_name: elasticsearch
    command: elasticsearch -Ecluster.name=gomato -Ebootstrap.memory_lock=true -Ehttp.port=9200 -Ehttp.cors.allow-origin="http://localhost:1358" -Ehttp.cors.enabled=true -Ehttp.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization -Ehttp.cors.allow-credentials=true
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
     - "9200:9200"
  dejavu:
    image: appbaseio/dejavu:latest
    container_name: dejavu
    ports:
     - "1358:1358"
    links:
      - elasticsearch
